print("Reglas de piedra-papel-tijera")
print("1. Se juega entre dos personas.")
print("2. Las dos personas se ponen frente a frente.")
print("3. A la cuenta de tres, cada una hace un gesto con la mano derecha.")
print("4. El gesto para 'piedra' es el puño cerrado.")
print("5. El gesto para 'papel' es la mano abierta.")
print("6. El gesto para 'tijera' es la mano cerrada con los dedos índice y medio extendidos.")
print("7. Piedra le gana a tijera.")
print("8. Tijera le gana a papel.")
print("9. Papel le gana a piedra.")
print("10. Si las dos personas hacen el mismo gesto, se repite el turno.")