print ("Yo: Hola gato")
print ("Gato: Miau")
print ("Yo: ¿Sabes qué pasó con el cable de mis audífonos?")
print ("Gato: Miau")
print ("Yo: Gracias por la información. Hasta luego.")
print ("Gato: Miau")