print("PROCESO PARA LAVAR PLATOS")
print("1. Preparar en el área de trabajo una esponja limpia y seca.")
print("2. Preparar detergente para lavar platos.")
print("3. Poner a calentar agua en un hervidor.")
print("4. Apilar los platos y vasos sucios en un lado del lavaplatos.")
print("5. Verter el agua caliente en un recipiente grande junto a los platos sucios.")
print("6. Poner dos o tres cucharadas de detergente en el agua caliente.")
print("7. Si el agua está demasiado caliente, agregar agua fría.")
print("8. Humedecer la esponja y agitar el agua con detergente hasta que se forme espuma.")
print("9. Usando la esponja mojada en el agua con detergente lavar los vasos uno por uno.")
print("10. Repasar cada vaso por dentro y por fuera con la esponja, apilarlo dentro del lavaplatos.")
print("11. Usando la esponja mojada en el agua con detergente lavar los platos uno por uno.")
print("12. Repasar cada plato por la parte superior e inferior con la esponja, apilarlo dentro del lavaplatos.")
print("13. Abrir el grifo de agua fría del lavaplatos.")
print("14. Enjuagar los vasos y platos uno por uno con agua fría para remover los restos de espuma.")
print("14. Apilar los vasos y platos enjuagados en la bandeja del lavaplatos y dejarlos escurrir por unos 10 o 15 minutos.")
print("15. Vaciar el agua con detergente en el interior del lavaplatos.")
print("16. Usando la espoja repasar el interior del recipiente para remover los restos de espuma.")
print("15. Enjuagar el recipiente con agua del grifo y apilarlo junto a los vasos y platos.")
print("16. Abrir el grifo y repasar el interior del lavaplatos con la esponja hasta que no queden residuos de detergente.")
print("17. Cerrar el grifo, estrujar la esponja hasta que quede seca y apartarla.")
print("17. Alistar un paño de algodón limpio y seco.")
print("18. Usando el paño, secar cada vaso por dentro y por fuera.")
print("19. Guardar cada vaso seco en la vitrina.")
print("20. Usando el paño, secar cada plato por arriba y por abajo.")
print("21. Guardar cada plato seco en la vitrina.")
print("22. Usando el paño, secar el recipiente por dentro y por fuera.")
print("23. Guardar el recipiente seco en la vitrina.")
print("24. Sacudir el paño de algodón y estirarlo sobre una superficie para que se seque.")